export const theme = {
  colors: {
    black: '#000000',
    gray: {
      1: '#121212',
      2: '#595959',
      3: '#767676',
      4: '#BDBDBD',
      5: '#E0E0E0',
      6: '#F3F3F3',
    },
    red: '#D32F2F',
    yellow: '#F9A825',
    green: '#4CAF50',
    primary: {
      default: '#238AFF',
      lighter: '#7CB9FF',
      darker: '#0062D1',
    },
    white: '#FFFFFF',
    purple: '#B47AFF',
    blue: '#238AFF',
  },
  fonts: {
    title: {
      xl: {
        fontWeight: 700,
        fontSize: '36px',
        lineHeight: '150%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      lg: {
        fontWeight: 700,
        fontSize: '24px',
        lineHeight: '150%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      md: {
        fontWeight: 700,
        fontSize: '21px',
        lineHeight: '150%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      sm: {
        fontWeight: 700,
        fontSize: '18px',
        lineHeight: '145%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      xs: {
        fontWeight: 700,
        fontSize: '16px',
        lineHeight: '150%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
    },
    text: {
      '2xl': {
        fontWeight: 400,
        fontSize: '18px',
        lineHeight: '145%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      xl: {
        fontWeight: 400,
        fontSize: '16px',
        lineHeight: '150%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      lg: {
        fontWeight: 400,
        fontSize: '14px',
        lineHeight: '140%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      md: {
        fontWeight: 400,
        fontSize: '12px',
        lineHeight: '150%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      sm: {
        fontWeight: 300,
        fontSize: '11px',
        lineHeight: '145%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
      xs: {
        fontWeight: 300,
        fontSize: '10px',
        lineHeight: '140%',
        fontFamily: 'Pretendard Variable',
        letterSpacing: '-2.5%',
      },
    },
  },
  borderRadius: {
    small: '10px',
    medium: '15px',
  },
  zIndex: {
    navigation: 950,
    dropdown: 1000,
    modal: 1050,
    tooltip: 1100,
  },
};
